version: 0.2

phases:
  
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x mvn
      - mvn package
      - echo $JAVA_HOME
  post_build:
    commands:
      - echo $(basename ./target/*.jar)
      - pwd

artifacts:
  files:
    - appspec.yml
    - target/*.jar
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
